# Permalinks
permalink: pretty

# Setup
name: Hongseo Ahn's Blog
url: 'https://honser.github.io'
title: Hongseo Ahn's Blog
tagline: 'A blog by <a href="https://instagram.com/overcoke" target="_blank">@hongseoahn</a>'
description: Systems Engineer
baseurl: ''
show_drafts: false
unpublished: true

#
exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Hongseo Ahn'
disqus_shortname: 'honser-github-io'
google_analytics: 'UA-151905772-1'

plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: '/blog/page:num'
sass:
    sass_dir: _sass
    style: :compressed


# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog'
  Categories:
    - '/blog/categories/'
    # - { Categories All: '/blog/categories/' }
    #- { Daily: '/blog/categories/#daily' }
    - { OpenStack: '/blog/categories/#openstack' }
    - { Kubernetes: '/blog/categories/#kubernetes' }
    - { SDN: '/blog/categories/#sdn' }
    # - { Django: '/blog/categories/#django' }
    # - { Python: '/blog/categories/#python' }
    - { Project: '/blog/categories/#project' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Tags:
    - '/blog/tags/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'
